### PR TITLE
Improve german language translation

### PR DESCRIPTION
**Pull request by ChuckNorrison**
Update HIDDENREVEALBUTTON, LNURLPAYAMOUNTSNOTICE, TXLIST

Replace Sat with Sats

### CODE REVIEW

**Comment by fiatjaf** [comment]
What if it is just 1 sat?

I've used "sat" everywhere because it fits both singular and plural (right?). If you start to add plural you'll have to account for the singular case everywhere, adding unnecessary complexity.

**Comment by ChuckNorrison** [comment]
Do we really have a 1 sat case? i thought we got a minimum sat behaviour. It should not be possible to make a 1 sat transaction. Only some circumstances for i.e. hidden message to reveal could end in 1 sat left to pay. But yes, you are absolutely right. Tried to respect the Directorate-General for Translation as recommended on wikipedia. Lets go back to 2006 where the "s" was not used.

**Comment by fiatjaf** [comment]
What is this Directorate-General thing? Why are you saying in 2006 the "s" was not used? I am confused.

**Comment by ChuckNorrison** [comment]
> What is this Directorate-General thing? Why are you saying in 2006 the "s" was not used? I am confused.

As described in wikipedia, they tried to add the "s" for everyone with the Euro after 2006

Sorry my editor removed your tabs, i restored them

**Comment by fiatjaf** [comment]
Let me know when you're done here.

**Comment by ChuckNorrison** [comment]
@fiatjaf iam fine with this, thanks a lot, the bot is awesome :)

**Pull request merged**
