### PR TITLE
add /sms command for receiving activation codes

### PR DESCRIPTION
**Pull request by pseudozach**
please check to make sure I didn't break anything in main or commands.
I can remove readme if you prefer not to have it or if it's wrong.

it should work like this ideally:
Screen Shot 2022-11-03 at 1 48 46 AM

### CODE REVIEW

**Comment by fiatjaf** [comment]
What is happening on that screenshot? I don't follow it.

**Comment by fiatjaf** [comment]
You're setting up a number specific for Twitter to send a confirmation SMS? Does it work only once and only for Twitter and it parses the message Twitter sends to display you the pin number nicely?

What other services are supported?
Can I use it receive SMSes from random people? (not that I want that)

**Comment by pseudozach** [comment]
> You're setting up a number specific for Twitter to send a confirmation SMS? Does it work only once and only for Twitter and it parses the message Twitter sends to display you the pin number nicely?
> 
> What other services are supported? Can I use it receive SMSes from random people? (not that I want that)

yes that's how sms4sats.com works. You want to register to an online service: facebook, twitter, telegram etc. but you don't want to use your own phone number. 
1- so you pay 3000 sats (subject to change 😄 )
2- you get a 1-time disposable number and give that number to twitter
3- they send the activation code, we show you that code.

There's an option to set "service" parameter as other which means random sms so it's possible to receive sms from unlisted services, people. The full supported list of countries/services are available online at [sms4sats.com](https://sms4sats.com/) or [via API](https://docs.sms4sats.com/) but I'm assuming some defaults for lntxbot just to not complicate the usage. Users can even call `/sms` directly and they should be able to get a number.

Another thing to note is backend uses `hold invoices` so the invoice is only settled if code is received and canceled if there's no code that's received within 20 minutes.

**Comment by fiatjaf** [comment]
Very nice.

**Pull request merged**
