### PR TITLE
Improve German translations

### PR DESCRIPTION
**Pull request by arbadacarbaYK**
Translation rework

### CODE REVIEW

**Comment by fiatjaf** [comment]
Thank you very much, but [52dd7d3](https://github.com/fiatjaf/lntxbot/pull/19/commits/52dd7d344cfb6592205ebde581bd05f05553a9d3) doesn't do what you want and just breaks the command, can you remove it?

The /coinflip@lntxbot is needed because Telegram will send commands always to the last mentioned bot, not to the bot that declares that commands specifically. It's a Telegram bug and we can't do anything about it.

**Comment by arbadacarbaYK** [comment]
The Please-read - part is about the @lntxbot, the two others are updates to the translation. Sorry, no idea how to stop one of the three

**Comment by fiatjaf** [comment]
Thank you very much Mr. Magician.

**Comment by arbadacarbaYK** [comment]
> 

Mrs 🧚🏻‍♀️ ! You are very welcome 😊

**Pull request merged**
